/** Project-owned generated visuals. Prompts: docs/image-generation.json. */
export type SiteImage = { src: string; alt: string; position?: string }
const img = (file: string, alt: string, position?: string): SiteImage => ({ src: `/images/generated/${file}.webp`, alt, position })
export const siteImages = {
  hero: img("hero-chain-link-4k", "Galvanized chain link fence with top rail in sharp focus against a clear blue sky", "object-[60%_50%]"),
  about: img("hd-chain-link-water", "Galvanized chain link fence with a steel post running along calm blue water"),
  established: img("hd-concertina", "Concertina razor wire on a green mesh security fence under a blue sky"),
  galvanized: img("hd-concertina", "Concertina razor wire on a green mesh security fence under a blue sky"),
  stainlessSteel: img("stainless", "Stainless steel welded square wire mesh sheet leaning against warm grey studio backdrop"),
  aluminium: img("aluminium", "Lightweight silver aluminium woven fine square insect screening mesh roll with curled end on grey studio surface"),
  pvc: img("hd-pvc-green-mesh", "Green plastic hexagonal mesh roll partly unrolled on a white background"),
  industrial: img("hd-chain-link-roll", "Galvanized chain link roll beside a chain link fence across open grass"),
  security: img("security", "Galvanized concertina razor wire neatly mounted on top of tall steel perimeter fence"),
  construction: img("construction", "Temporary steel welded mesh fencing panels on concrete feet enclosing an orderly active building site"),
  agricultural: img("doc-hexa-chicken", "Hexagonal chicken wire fence on concrete posts along a green crop field"),
  residential: img("hd-pvc-garden-roll", "Green PVC hexagonal mesh roll and fence around a raised vegetable garden bed"),
  commercial: img("commercial-welded", "Grey welded wire mesh fence panels beside a commercial building"),
  aboutHero: img("about-hero", "Wide organized wire mesh fabrication workshop with mesh rolls and steel panels"),
  productsHero: img("products-hero", "Beautiful lineup of steel chain link rolls"),
  solutionsHero: img("solutions-hero", "Architectural panorama of long welded mesh perimeter across landscaped industrial property with clear fence in foreground"),
  contactHero: img("contact-hero", "Tidy fencing materials showroom workspace with mesh sample panels"),
  notFound: img("diamond-mesh", "Silver aluminium expanded diamond mesh sheet with dimensional diamond openings on warm neutral studio surface"),
  concertina: img("concertina", "Single freestanding galvanized concertina razor wire coil on neutral grey studio floor"),
  rbt: img("rbt", "Close-up galvanized razor barbed tape coil on neutral grey studio floor"),
  chainLink: img("chain-link", "Single silver galvanized chain link mesh roll partially unrolled on neutral grey studio floor"),
  barbedWire: img("barbed-wire", "A tidy coil of double strand galvanized barbed wire on warm grey studio floor with one strand extending towards camera"),
  mosquitoWireMesh: img("mosquito-mesh", "Fine galvanized square insect screen mesh roll partially unrolled on grey studio surface"),
  weldedMesh: img("welded-mesh", "Freestanding galvanized welded steel square grid panels and a partly rolled mesh sheet on neutral studio floor"),
  hexagonal: img("hexagonal", "Galvanized hexagonal chicken wire roll partially unrolled on grey studio floor"),
  stainlessMosquito: img("stainless-mosquito", "Fine stainless steel insect screen mesh in a silver aluminium window sample frame on studio surface"),
  stainlessProduct: img("stainless-product", "Stainless steel welded wire mesh panels with accurate square openings"),
  aluminiumProduct: img("aluminium-product", "Rolled aluminium fine woven square wire mesh with lightweight silver sheen on warm grey studio floor"),
  diamondBarfi: img("diamond-mesh", "Silver aluminium expanded diamond mesh sheet with dimensional diamond openings on warm neutral studio surface"),
  pvcGarden: img("pvc-garden-fence-installed", "Dark green PVC coated hexagonal mesh fence on wooden posts around a vegetable garden bed"),
  pvcWire: img("pvc-panel", "Green PVC coated welded square mesh roll and small panel on neutral studio floor"),
  mosquitoNet: img("mosquito-net", "Charcoal fine synthetic mosquito net stretched in a window frame with airy softly lit room behind"),
  shadeNet: img("shade-net", "Green woven shade net stretched over nursery plants on simple metal supports"),
  fibreGlass: img("fibre-glass-waterproofing", "White glass fibre mesh embedded in grey waterproofing coating on a concrete roof terrace, with a roller and coating tub"),
} as const
