/** Project-owned generated visuals. Prompts: docs/image-generation.json. */
export type SiteImage = { src: string; alt: string; position?: string }
const img = (file: string, alt: string, position?: string): SiteImage => ({ src: `/images/generated/${file}.webp`, alt, position })
export const siteImages = {
  hero: img("hero", "A premium industrial warehouse perimeter with perfectly installed charcoal welded steel mesh fence receding to the right", "object-[60%_50%]"),
  about: img("about", "Neatly stacked galvanized welded mesh panels in a tidy fabrication workshop"),
  galvanized: img("galvanized", "Three galvanized steel chain link mesh rolls on a clean warm grey studio floor"),
  stainlessSteel: img("stainless", "Stainless steel welded square wire mesh sheet leaning against warm grey studio backdrop"),
  aluminium: img("aluminium", "Lightweight silver aluminium woven fine square insect screening mesh roll with curled end on grey studio surface"),
  pvc: img("pvc", "Green PVC coated hexagonal garden mesh roll"),
  industrial: img("industrial", "Long charcoal steel mesh fence and access gate enclosing a modern industrial warehouse in daylight"),
  security: img("security", "Galvanized concertina razor wire neatly mounted on top of tall steel perimeter fence"),
  construction: img("construction", "Temporary steel welded mesh fencing panels on concrete feet enclosing an orderly active building site"),
  agricultural: img("agricultural", "Wire mesh farm fence along a lush green orchard and farmland"),
  residential: img("residential", "Elegant green wire mesh garden boundary at a modern home"),
  commercial: img("commercial", "Steel welded mesh boundary and gate beside modern commercial campus"),
  aboutHero: img("about-hero", "Wide organized wire mesh fabrication workshop with mesh rolls and steel panels"),
  productsHero: img("products-hero", "Beautiful lineup of steel chain link rolls"),
  solutionsHero: img("solutions-hero", "Architectural panorama of long welded mesh perimeter across landscaped industrial property with clear fence in foreground"),
  contactHero: img("contact-hero", "Tidy fencing materials showroom workspace with mesh sample panels"),
  notFound: img("diamond-mesh", "Silver aluminium expanded diamond mesh sheet with dimensional diamond openings on warm neutral studio surface"),
  concertina: img("concertina", "Single freestanding galvanized concertina razor wire coil on neutral grey studio floor"),
  rbt: img("rbt", "Close-up galvanized razor barbed tape coil on neutral grey studio floor"),
  chainLink: img("chain-link", "Single silver galvanized chain link mesh roll partially unrolled on neutral grey studio floor"),
  barbedWire: img("barbed-wire", "A tidy coil of double strand galvanized barbed wire on warm grey studio floor with one strand extending towards camera"),
  mosquitoWireMesh: img("mosquito-mesh", "Fine galvanized square insect screen mesh roll partially unrolled on grey studio surface"),
  weldedMesh: img("welded-mesh", "Freestanding galvanized welded steel square grid panels and a partly rolled mesh sheet on neutral studio floor"),
  hexagonal: img("hexagonal", "Galvanized hexagonal chicken wire roll partially unrolled on grey studio floor"),
  stainlessMosquito: img("stainless-mosquito", "Fine stainless steel insect screen mesh in a silver aluminium window sample frame on studio surface"),
  stainlessProduct: img("stainless-product", "Stainless steel welded wire mesh panels with accurate square openings"),
  aluminiumProduct: img("aluminium-product", "Rolled aluminium fine woven square wire mesh with lightweight silver sheen on warm grey studio floor"),
  diamondBarfi: img("diamond-mesh", "Silver aluminium expanded diamond mesh sheet with dimensional diamond openings on warm neutral studio surface"),
  pvcGarden: img("pvc-garden", "Green PVC coated hexagonal chicken mesh installed around a raised garden bed"),
  pvcWire: img("pvc-panel", "Green PVC coated welded square mesh roll and small panel on neutral studio floor"),
  mosquitoNet: img("mosquito-net", "Charcoal fine synthetic mosquito net stretched in a window frame with airy softly lit room behind"),
  shadeNet: img("shade-net", "Green woven shade net stretched over nursery plants on simple metal supports"),
  birdNet: img("bird-net", "Fine black bird protection net installed over a sunny apartment balcony"),
} as const
